### ISSUE TITLE
GitHub action fails for Quay.io

### ISSUE THREAD

**Issue by tboerger** [christian-korneck/docker-pushrm#13]
**Describe the problem or bug**
When trying to upload the README.md to quay.io the GitHub action fails with a logging message like `CSRF token was invalid or missing`.

**docker-pushrm version**
Version used by your GitHub actions

**Docker CLI version and platform**
Shipped with ubuntu-latest within GitHub actions

**if possible: registry server version**
quay.io

**exact command that you're running**
```
jobs:
  quayio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Push readme
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_APIKEY: ${{ secrets.QUAY_APIKEY }}
        with:
          destination_container_repo: quay.io/webhippie/alpine
          provider: quay
          readme_file: README.md
```

**debug output**
```
/usr/bin/docker run --name dockeriochkodockerpushrm1_bb3d34 --label cc4956 --workdir /github/workspace --rm -e APIKEY__QUAY_IO -e INPUT_DESTINATION_CONTAINER_REPO -e INPUT_PROVIDER -e INPUT_README_FILE -e INPUT_SHORT_DESCRIPTION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/alpine/alpine":"/github/workspace" docker.io/chko/docker-pushrm:1  "--provider" "quay" "--short" "" "--file" "README.md" "--debug" "quay.io/webhippie/alpine"
level=debug msg="root cmd init config"
level=debug msg="home dir: /github/home"
level=debug msg="subcommand \"pushrm\" called"
level=debug msg="Using target: quay.io/webhippie/alpine:latest"
level=debug msg="using README file: README.md"
level=debug msg="server: quay.io"
level=debug msg="namespace: webhippie"
level=debug msg="repo: alpine"
level=debug msg="tag: latest"
level=debug msg="repo provider: quay"
level=debug msg="Quay.GetAuthident called"
level=debug msg="Using Docker creds:  ********"
level=debug msg="Quay.Pushrm called"
level=debug msg="util.GetApikey called"
level=debug msg="apikey: ********"
level=debug msg="push readme, response body: {\"message\": \"CSRF token was invalid or missing.\"}\n"
level=debug msg="push README, status code: 403"
level=debug msg="error pushing README, bad status code for response: 403 Forbidden. Try \"docker logout\" and \"docker login\""
level=error msg="error pushing readme to repo server. See error message below. Run with \"--debug\" for more details. \n\nerror pushing README, bad status code for response: 403 Forbidden. Try \"docker logout\" and \"docker login\""
```

**Additional context**
You can see the failed build at https://github.com/dockhippie/alpine/runs/1581683462?check_suite_focus=true, on the same workflow run you can see that Docker Hub was working fine.
