### ISSUE TITLE
GitLab Pipeline troubleshooting

### ISSUE THREAD

**Issue by letompouce** [christian-korneck/docker-pushrm#15]
## description

In a GitLab pipeline, the `chko/docker-pushrm` image seem to not pick the `PUSHRM_TARGET` environment variable.

## upstream image: ko

This is a basic job. If you're not familiar with GitLab CICD, the `variables:` defined here will be available to the job as environment variables. The `$CI_...` variables are predefined by the GitLab Runner, and the `$DOCKER_...` ones are defined at the project level. Believe me, they are correctly defined and available :-)

```yaml
pushrm:
  stage: release
  image: chko/docker-pushrm
  variables:
    DOCKER_USER: $DOCKER_HUB_LOGIN
    DOCKER_PASS: $DOCKER_HUB_PASSWORD
    PUSHRM_SHORT: Hello world image.
    # GitLab will evaluate variables once only, so we can not use $CONTAINER_IMAGE here.
    PUSHRM_TARGET: "docker.io/$DOCKER_HUB_REPOSITORY/$CI_PROJECT_NAME"
    PUSHRM_DEBUG: 1
    PUSHRM_FILE: $CI_PROJECT_DIR/README.md
  script:
    - docker-pushrm
  ```
The job fails:
```
Executing "step_script" stage of the job script
Using docker image sha256:1b4adda359ab661ef05cdfefff8820ff9706784d629b154bd3d9b8aaffa113c2 for chko/docker-pushrm with digest chko/docker-pushrm@sha256:f6abb69e71e5718c18802eac84922cf02f2b5a47eced516de271afe24a7b458b ...
level=debug msg="root cmd init config"
level=debug msg="home dir: /"
level=debug msg="subcommand \"pushrm\" called"
level=error msg="Invalid [IMAGE] argument - missing namespace. Example: docker.io/mynamespace/myrepo:latest"
Cleaning up file based variables
ERROR: Job failed: exit code 1
```
From the debug messages, we can assume the `$PUSHRM_DEBUG`  variable was effective, but it seem `$PUSHRM_TARGET` was not seen by `docker-pushrm`. I tried to hardcode it right in the `variables:PUSHRM_TARGET` statement but it didn't work either, so it is not about GitLab's variables evaluation.

## custom image with entrypoint: ok

I created a custom image with an `entrypoint.sh` script which basically dumps `env`, in order to troubleshoot the environment variables.

The Dockerfile:
```
FROM chko/docker-pushrm:latest as builder
FROM alpine:latest
COPY --from=builder /docker-pushrm /
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
```
The entrypoint script:
```shell
#!/bin/sh
>&2 echo "[+] debug env..."
env | sort | grep PUSHRM
>&2 echo "[+] docker-pushrm"
/docker-pushrm
```

Using the very same pipeline job but using this custom image, it works:
```
Executing "step_script" stage of the job script
Using docker image sha256:325bcd222af62b99975287ce9ac971abf373e9b59d023802c369b79134e4d44e for letompouce/pushrm with digest letompouce/pushrm@sha256:3b4a5711ef79ca6391252fb2f6aa84caab79479d5281eed072f68d636baba197 ...
[+] debug env...
DOCKER_ENV_PUSHRM_DEBUG=1
DOCKER_ENV_PUSHRM_FILE=/builds/l3tompouce/org/lab/pushrm/README.md
DOCKER_ENV_PUSHRM_SHORT=Hello world image.
DOCKER_ENV_PUSHRM_TARGET=docker.io/letompouce/pushrm
PUSHRM_DEBUG=1
PUSHRM_FILE=/builds/l3tompouce/org/lab/pushrm/README.md
PUSHRM_SHORT=Hello world image.
PUSHRM_TARGET=docker.io/letompouce/pushrm
[+] docker-pushrm
level=debug msg="root cmd init config"
level=debug msg="home dir: /root"
level=debug msg="subcommand \"pushrm\" called"
level=debug msg="Using target: docker.io/letompouce/pushrm:latest"
level=debug msg="using README file: /builds/l3tompouce/org/lab/pushrm/README.md"
level=debug msg="server: docker.io"
level=debug msg="namespace: letompouce"
level=debug msg="repo: pushrm"
level=debug msg="tag: latest"
level=debug msg="repo provider: dockerhub"
level=debug msg="Dockerhub.GetAuthident called"
level=debug msg="using credentials for user letompouce from generic env var"
level=debug msg="Using Docker creds: letompouce ********"
level=debug msg="Dockerhub.Pushrm called"
level=debug msg="retrieve Dockerhub jwt token, status code: 200"
level=debug msg="push readme, response body: {\"user\": \"letompouce\", \"name\": \"pushrm\", \"namespace\": \"letompouce\", \"repository_type\": \"image\", \"status\": 1, \"description\": \"Hello world image.\", \"is_private\": false, \"is_automated\": false, \"can_edit\": true, \"star_count\": 0, \"pull_count\": 62, \"last_updated\": \"2021-07-17T08:10:08.663623Z\", \"is_migrated\": false, \"collaborator_count\": 0, \"affiliation\": \"owner\", \"hub_user\": \"letompouce\", \"has_starred\": false, \"full_description\": \"# pushrm test\\n\\nthis is a test.\\n\", \"permissions\": {\"read\": true, \"write\": true, \"admin\": true}}"
level=debug msg="push README, status code: 200"
level=debug msg="content validation successfull, readme successfully pushed to repo server"
Cleaning up file based variables
Job succeeded
```
Note that at this point, `PUSHRM_TARGET` is still defined in the `variables:` with `"docker.io/$DOCKER_HUB_REPOSITORY/$CI_PROJECT_NAME"` so it is definitively not a variable evaluation issue.

## what now?

I feel like I'm missing something obvious, but what? Any help would be appreciated!

## additionnal info

**docker-pushrm version**

1.6.0 from the `chko/docker-pushrm` image

**Docker CLI version and platform**

Docker 20.10.6 / Debian 10

**Comment by christian-korneck** [comment]
@letompouce - good catch, thanks for reporting this!

I did not yet look at it, but it sounds like the `script: "/docker-pushrm"` puts an argument behind the entrypoint command. So `/docker-pushrm` (pure entrypoint) becomes `/docker-pushrm /docker-pushrm` (entrypoint plus gitlab `script`). Your custom entrypoint script ignores this argument (doesn't pass it to the executable), that's why I guess it works.

Unfortunately it seems in a gitlab job definition a `script: "non-empty-string"` is mandatory. If it was possible to not set `script`, it would probably work. So we need a different solution. I'll try to repro it later to see how it can be fixed.

**Comment by christian-korneck** [comment]
my assumption was partly correct, but the problem goes deeper. Gitlab is actually trying to run something like:

```
/docker-pushrm
sh
-c
if [ -x /usr/local/bin/bash ]; then
	exec /usr/local/bin/bash 
elif [ -x /usr/bin/bash ]; then
	exec /usr/bin/bash 
elif [ -x /bin/bash ]; then
	exec /bin/bash 
elif [ -x /usr/local/bin/sh ]; then
	exec /usr/local/bin/sh 
elif [ -x /usr/bin/sh ]; then
	exec /usr/bin/sh 
elif [ -x /bin/sh ]; then
	exec /bin/sh 
elif [ -x /busybox/sh ]; then
	exec /busybox/sh 
else
	echo shell not found
	exit 1
fi
```

It seems Gitlab doesn't support minimal `FROM SCRATCH` images (without shell, coreutils, etc) that only contain an executable  currently:
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26501

Maybe we need to add an Alpine image. I'll poke a bit more tomorrow.

**Comment by letompouce** [comment]
> It seems Gitlab doesn't support minimal `FROM SCRATCH` images (without shell, coreutils, etc) that only contain an executable currently:
> https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26501

Ah damn, that was the obvious thing I missed! Well, this Alpine based image is 14,5Mb instead of 9, I guess I can survive with that for the time being.

**Comment by christian-korneck** [comment]
@letompouce I just pushed a new version of the container image (`v1.8.0`), which is now based on `busybox`. With that a `.gitlab-ci.yml` like this works now for me:

```
stages:
  - release

pushrm:
  stage: release
  image:
    name: chko/docker-pushrm
    entrypoint: ["/bin/sh", "-c", "/docker-pushrm"]
  variables:
    DOCKER_USER: $DOCKER_USER
    DOCKER_PASS: $DOCKER_PASS
    PUSHRM_SHORT: My short description
    PUSHRM_TARGET: docker.io/$DOCKER_USER/my-repo
    PUSHRM_DEBUG: 1
    PUSHRM_FILE: $CI_PROJECT_DIR/README.md
  script: "/bin/true"
```

(also documented [here](https://github.com/christian-korneck/docker-pushrm#use-with-gitlab-cicd))

This basically satisfies GitLab's mandatory script execution and prevents that any arguments get passed to `/docker-pushrm` (so it only uses the env vars). It looks a bit ugly, but at least the Docker image change shouldn't change behaviour for existing users (we basically just added some more files to the image, but didn't change `entrypoint`, etc) _and_ we have a working recipe for a gitlab job.

Does this solve your issue?
